name: flutter_chat_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.e
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_localizations:
   # sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.4

  # Firebase
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  fake_cloud_firestore: ^1.2.1
  firebase_storage: ^10.2.7
  flutterfire_ui: ^0.3.6
  #firebase_auth_admin: ^0.9.5
  firebase_database: ^9.0.8
  #firebase_analytics: ^9.1.0

  sqflite: ^2.0.2

  get: ^4.6.1

  #Country code
  phone_form_field: ^4.5.1
  dart_countries: ^2.1.0
  #######

  # Whatsapp library's
  line_icons:
  flutter_svg: ^1.0.3
  animate_do: ^2.1.0
  bubble: ^1.2.1
  chat_bubbles: ^1.2.0
  audioplayers: ^0.20.1
  #######

  syncfusion_flutter_gauges: ^19.4.48
  loading_animation_widget: ^1.1.0+0
  image_picker_widget: ^2.0.2
  image_cropper: 1.4.1
  skeletons: ^0.0.3
  shimmer_animation: ^2.1.0+1
  json_annotation: ^4.4.0
  path: ^1.8.0
  get_storage: ^2.0.3
  path_provider: ^2.0.9
  network_to_file_image: ^3.1.0
  multiavatar: ^0.1.5
  flutter_sheet_localization: ^5.1.1
  csv: ^5.0.1

  circular_profile_avatar: ^2.0.5
  #cupertino_list_tile: ^0.2.1

  enough_platform_widgets: ^0.3.0

  flutter_platform_widgets: ^1.20.0

  animated_theme_switcher: ^2.0.1
  adaptive_theme: ^2.3.0

  ionicons: ^0.1.2

  pin_code_fields: ^7.3.0

  flutter_contacts: ^1.1.3
  contacts_service: ^0.6.3
  permission_handler: ^8.1.6 #^9.2.0

  #chat_ui_kit: ^1.3.0

  pull_to_refresh: ^2.0.0

  fireflutter: ^0.2.15
  #extended: ^0.1.9

  flutter_slidable: ^1.2.0

  #geolocator: ^8.2.0
  #geocoder: ^0.2.1
  #mobile_number: ^1.0.4

  #country_codes: ^2.1.1

  #excel: ^1.0.0
  #excel: ^2.0.0-null-safety-3

  #flutter_offline: ^2.0.0


  #Flutter Firebase Chat
  flutter_firebase_chat_core: ^1.5.2
  flutter_chat_ui: ^1.5.5

  http: ^0.13.4
  image_picker: ^0.8.4+4
  mime: ^1.0.1
  open_file: ^3.2.1
  faker: ^2.0.0
  file_picker: ^4.3.2

  hive: ^2.0.6
  hive_flutter: ^1.1.0

  badges: ^2.0.2
  #social_media_recorder: ^0.1.61

  uuid: ^3.0.5
  animated_text_kit: ^4.2.1
  provider: ^6.0.2
  record: ^3.0.2

  #sortedmap: ^0.5.1
  comparator_sorted_map: ^1.0.5
  #stream_chat_flutter: ^3.5.1

  just_audio_libwinmedia: ^0.0.4
  just_audio: ^0.9.20
  rxdart: ^0.27.3
  audio_session: ^0.1.6+1

  #audio_chat
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^10.1.0
  lottie: ^1.2.2
  flutter_ffmpeg: ^0.4.2

  flutter_vector_icons: ^1.0.0

  getwidget: ^2.0.5

  #chat_composer: ^1.0.1
  #bloc: ^8.0.3
  #flutter_bloc: ^8.0.1
  #fluttertoast: ^8.0.9
  #meta: ^1.7.0
  #flutter_sound_lite: ^8.5.0

  #pausable_timer: ^1.0.0+4
  stop_watch_timer: ^1.4.0

  #flutter_sound: ^9.2.10

  #media_info: ^0.10.0

  voice_message_package: ^0.0.66
  just_waveform: ^0.0.2
  #audio_waveforms: ^0.0.3+2

  audio_waveforms:
    git:
      url: https://github.com/MohammedSharaf22/audio_waveform.git

  wechat_assets_picker: ^7.1.2
  camera: ^0.9.4+21
  #images_picker: ^1.2.11
  #advance_image_picker: ^0.1.6+1
  photo_view: ^0.13.0

  agora_rtc_engine: ^4.0.7 #^5.1.0

  video_compress: ^3.1.0
  flutter_image_compress: ^1.1.0
  #video_thumbnail: ^0.5.0
  video_player: ^2.4.0

  #timeago: ^3.2.2

  #dependency_overrides:
 # flutter_slidable: ^0.6.0 #^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

  flutter_lints: ^1.0.0

  #flutter pub run build_runner build --delete-conflicting-outputs
  #flutter packages pub run build_runner build


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #generate: true
  assets:
    - assets/images/
    - assets/avatars/

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#flutter_intl:
  #enabled: true
